[package]
name = "shared_keys"
type = "contract"
authors = [""]
compiler_version = ">=0.34.0"


[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/authwit" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/compressed-string" }
address_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/address-note" }
easy_private_state = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/easy-private-state" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/noir-protocol-circuits/crates/types" }
value_note = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.56.0", directory = "noir-projects/aztec-nr/value-note" }
